version: '3'

includes:
  github:
    taskfile: github.Taskfile.yml
    dir: .

  deploy:
    taskfile: deploy/Taskfile.yml
    dir: deploy

  infra:
    taskfile: infra/Taskfile.yml
    dir: infra

tasks:
  fixAll:
    desc: Apply all automatic fixes
    deps:
      - github:fixLint
      - deploy:fixFormatting
      - deploy:fixLint
      - infra:fixFormatting
      - infra:fixLint
