config:
  medusa-platform:delegationFolder: folders/523003355329
  medusa-platform:pulumiOrganization: jakub-trzebiatowski-medusa-software
  gcp:project: ms-central-108271b9
environment:
  - platform/gcp
